PROJ_NAME = Adders and Subtractors
TEST_PROJ_NAME = Test_$(PROJ_NAME)

SRC =src/fulladders_functions.c
SRC =src/fullsubtractors_functions.c
SRC =src/halfadders_functions.c
SRC =src/halfsubtractors_functions.c

INC_H = inc/headers.h

MAIN = main.c/fulladders.c
MAIN = main.c/fullsubtractors.c
MAIN = main.c/halfadders.c
MAIN = main.c/halfsubtactor.c
